#!/bin/bash

## Copyright timetoexpire.co.uk 2022 (MIT License) https://github.com/timetoexpire/shelltoolset

ipv4_regex () {
  ip="$1"
  echo -n "DEBUG: IP $ip "
  if [[ ! $ip =~ ^([01]?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])\.([01]?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])\.([01]?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])\.([01]?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])$ ]]; then
    echo "Out range IPv4 "
  fi
}

ipv4_regex 0.0.0.0
ipv4_regex 1.2.3.4
ipv4_regex 012.004.000.199
ipv4_regex 255.255.255.255
ipv4_regex 255.255.255.256
ipv4_regex 0.0.300.0
ipv4_regex 0..2.3
ipv4_regex 0.1
ipv4_regex 0.1f.2.3
